In [1]:
import numpy as np
import time

In [8]:
#executiom performance
#large dataset
size = 10_000_000

#python lists
py_list = list(range(size))

start = time.time()
list_square = [x**2 for x in py_list]
end = time.time()
print(f"the time required for list = {end - start}secs")

#numpy arrays
np_array = np.array(py_list)

start = time.time()
array_square = np_array**2
end = time.time()
print(f"the time requires for numpy array = {end - start}secs")


the time required for list = 1.7045814990997314secs
the time requires for numpy array = 0.047150373458862305secs


In [10]:
# memory usage
import sys
print("python list size:", sys.getsizeof(py_list)*len(py_list))
print("numpy array size:", np_array.nbytes)


python list size: 800000560000000
numpy array size: 80000000


In [14]:
#creating numpy arrays from list
arr = np.array([1,2,3,4])
print(arr, type(arr))

arr1 = np.array([1,2,3,4,"prime"])
print(arr1, type(arr1))

arr2 = np.array([[1,2,3], [3,4,5]])
print(arr2, type(arr2), arr2.shape)

[1 2 3 4] <class 'numpy.ndarray'>
['1' '2' '3' '4' 'prime'] <class 'numpy.ndarray'>
[[1 2 3]
 [3 4 5]] <class 'numpy.ndarray'> (2, 3)


In [20]:
#creating numpy arrays 
arr1 = np.zeros((5,4))
print(arr1, arr1.shape)

arr2 = np.ones((3,4))
print(arr2, arr2.shape)

arr3 = np.full((2,3),4)
print(arr3)

arr4 = np.eye(4)
print(arr4)

arr5 = np.arange(1, 20, 2)
print(arr5)

arr6 = np.linspace(0, 10, 5)
print(arr6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] (5, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)
[[4 4 4]
 [4 4 4]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[ 1  3  5  7  9 11 13 15 17 19]
[ 0.   2.5  5.   7.5 10. ]


In [21]:
#array properties
arr = np.array([[2,3,3], [5,6,6], [4,5,7]])

print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

str_arr = np.array([1, 2, 3], dtype="U")
print(str_arr, str_arr.dtype)

float_arr = np.array([1, 2, 3], dtype="float64")
print(str_arr, float_arr.dtype)

int_arr = float_arr.astype(np.int64)
print(int_arr, int_arr.dtype)



(3, 3)
9
2
int64
['1' '2' '3'] <U1
['1' '2' '3'] float64
[1 2 3] int64
