In [3]:
import numpy as np
#reshaping
arr = np.array([2,3,4,4,5,4])
print(arr.shape)

reshaped = arr.reshape((2,3))
print(reshaped, reshaped.shape)

flattened = reshaped.flatten()#converts 2D=>1D
print(flattened, flattened.shape)

(6,)
[[2 3 4]
 [4 5 4]] (2, 3)
[2 3 4 4 5 4] (6,)


In [5]:
#indexing
arr = np.array([4, 5, 6, 3, 2])
print(arr[0])

arr = np.array([[1,3,4], [3,6,7], [3,8,9], [9,0,4]])
print(arr[0][1])
print(arr[1][2])

#fancy indexing
xyz = np.array([2,4,7,0,8])
idx = [0,1,4]
print(xyz[idx])

#boolean indexing
print(xyz[xyz>2])
print(xyz[xyz % 2 == 0])

4
3
7
[2 4 8]
[4 7 8]
[2 4 0 8]


In [7]:
#slicing
arr = np.array([1,3,4,5,7,9])
print(arr[2:4])
print(arr[:5])
print(arr[2:])
print(arr[::3])

[4 5]
[1 3 4 5 7]
[4 5 7 9]
[1 5]


In [8]:
#copy v/s view by slicing
#sliced list is a copy
py_list = [1, 2, 3, 4, 5]
copy_list = py_list[1:4] #[2, 3, 4]
copy_list[1] = 333

print(copy_list)
print(py_list)

#Sliced array is a view
np_arr = np.array([1, 2, 3, 4, 5])
view_arr = np_arr[1:4] #[2, 3, 4]
view_arr[1] = 333

print(view_arr)
print(np_arr)

#Creating a copy


[2, 333, 4]
[1, 2, 3, 4, 5]
[  2 333   4]
[  1   2 333   4   5]
